## Give some statistics about Dataset

In [4]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from scipy.stats import chi2

In [2]:
# read dataframe

df = pd.read_csv('cust_seg.csv')

In [3]:
df.head()

custid  sex  AqChannel  region  Marital_status  segment  pre_usage  \
0      70    0          4       1               1        1         57   
1     121    1          4       2               1        3         68   
2      86    0          4       3               1        1         44   
3     141    0          4       3               1        3         63   
4     172    0          4       2               1        2         47   

   Post_usage_1month  Latest_mon_usage  post_usage_2ndmonth  
0                 52              49.2                 57.2  
1                 59              63.6                 64.9  
2                 33              64.8                 36.3  
3                 44              56.4                 48.4  
4                 52              68.4                 57.2

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   custid               200 non-null    int64  
 1   sex                  200 non-null    int64  
 2   AqChannel            200 non-null    int64  
 3   region               200 non-null    int64  
 4   Marital_status       200 non-null    int64  
 5   segment              200 non-null    int64  
 6   pre_usage            200 non-null    int64  
 7   Post_usage_1month    200 non-null    int64  
 8   Latest_mon_usage     200 non-null    float64
 9   post_usage_2ndmonth  200 non-null    float64
dtypes: float64(2), int64(8)
memory usage: 15.8 KB


In [85]:
df.describe()

custid        sex   AqChannel      region  Marital_status  \
count  200.000000  200.00000  200.000000  200.000000      200.000000   
mean   100.500000    0.54500    3.430000    2.055000        1.160000   
std     57.879185    0.49922    1.039472    0.724291        0.367526   
min      1.000000    0.00000    1.000000    1.000000        1.000000   
25%     50.750000    0.00000    3.000000    2.000000        1.000000   
50%    100.500000    1.00000    4.000000    2.000000        1.000000   
75%    150.250000    1.00000    4.000000    3.000000        1.000000   
max    200.000000    1.00000    4.000000    3.000000        2.000000   

          segment   pre_usage  Post_usage_1month  Latest_mon_usage  \
count  200.000000  200.000000         200.000000        200.000000   
mean     2.025000   52.230000          52.775000         63.174000   
std      0.690477   10.252937           9.478586         11.242137   
min      1.000000   28.000000          31.000000         39.600000   
25%      2.000000   44.000000          45.750000         54.000000   
50%      2.000000   50.000000          54.000000         62.400000   
75%      2.250000   60.000000          60.000000         70.800000   
max      3.000000   76.000000          67.000000         90.000000   

       post_usage_2ndmonth  
count           200.000000  
mean             58.052500  
std              10.426445  
min              34.100000  
25%              50.325000  
50%              59.400000  
75%              66.000000  
max              73.700000

# 1. Card usage has been improved significanlty from last year usage which is 50. 
(Hint: comparing card usage of post campaign of 1 month with last year hypothesized value 50)



## T-test
#### using one sample t-test because comparing card usage of post campaign of month with hypothesized value 50

- The null hypothesis (H0) is that the true difference between these group means is zero.
- The alternate hypothesis (Ha) is that the true difference is different from zero.

#### In this problem 
- Null hypothesis is that the card usage has not improved from last year usage
- Alternate hypothesis is the card usage has beeen improved significantly from last year usage

In [11]:
ttest,p_value = stats.ttest_1samp(df['Post_usage_1month'],50)

In [12]:
print(p_value)

5.120919460716355e-05


In [13]:
if p_value < 0.05:
    print('Reject the null hypothesis,there is difference between mean of this two variables ')
else:
    print('Fail to Reject the null hypothesis,there is no difference between mean of this two variables ')

Reject the null hypothesis,there is difference between mean of this two variables 


#### Reject the null hypothesis means there is no valid evidence to fail to reject the null hypothesis, so accepting the alternate hypotheis that the card usage has been improved significantly from last year

# 2. The last campaign was successful in terms usage of credit card. 
(Hint comparning means for card usage of pre and post usage of campaign).


## T- test

#### Using paired t-test because comparing mean's of card usage of pre and post usage of campaign that the pre and post usage are from same population like before and after

#### In this problem
- Null hypothesis is last campaign was not succesful in terms usage of creditcard
- Alternate hypothesis is  last campaign was scuccesful in terms usage of credit card

In [14]:
df.head()

custid  sex  AqChannel  region  Marital_status  segment  pre_usage  \
0      70    0          4       1               1        1         57   
1     121    1          4       2               1        3         68   
2      86    0          4       3               1        1         44   
3     141    0          4       3               1        3         63   
4     172    0          4       2               1        2         47   

   Post_usage_1month  Latest_mon_usage  post_usage_2ndmonth  
0                 52              49.2                 57.2  
1                 59              63.6                 64.9  
2                 33              64.8                 36.3  
3                 44              56.4                 48.4  
4                 52              68.4                 57.2

In [20]:
_,p_value = stats.ttest_rel(a = df['pre_usage'],b = df['Post_usage_1month'])

In [21]:
print(p_value)

0.3868186820914985


In [22]:
if p_value < 0.05:
    print('Reject the null hypothesis,there is difference between mean of this two variables ')
else:
    print('Fail to Reject the null hypothesis,there is no difference between mean of this two variables ')

Fail to Reject the null hypothesis,there is no difference between mean of this two variables 


In [26]:
_,p_value = stats.ttest_rel(a = df['pre_usage'],b = df['Latest_mon_usage'])

In [27]:
print(p_value)

6.336089707623977e-42


In [28]:
if p_value < 0.05:
    print('Reject the null hypothesis,there is difference between mean of this two variables ')
else:
    print('Fail to Reject the null hypothesis,there is no difference between mean of this two variables ')

Reject the null hypothesis,there is difference between mean of this two variables 


In [23]:
_,p_value = stats.ttest_rel(a = df['pre_usage'],b = df['post_usage_2ndmonth'])

In [24]:
print(p_value)

4.295733828012836e-16


In [25]:
if p_value < 0.05:
    print('Reject the null hypothesis,there is difference between mean of this two variables ')
else:
    print('Fail to Reject the null hypothesis,there is no difference between mean of this two variables ')

Reject the null hypothesis,there is difference between mean of this two variables 


#### observation
- From pre usage to post usage 1st month the test result is  fail to reject the null hypothesis,that there is no difference in the usage of credit card 
- From preusage to post usage 2nd month and latest month usage,the null hypothesis is rejected,there is difference in the usage of credit card from 2nd month of campaign
- By this test the last campaign was succesfull in the usage of credit card

# 3. Is there any difference between males and females in terms of credit card usage? 
(Hint: Comparing means of Card usage for males and females)


## T-test

#### using two sample t-test because comparing means of two groups like mean and female usage of credit card

#### In this problem:
- Ho is there is no difference between males and females in term of credit card usage
- Ha is there is difference between males and females in term of credit card usage

In [55]:
df.head()

custid  sex  AqChannel  region  Marital_status  segment  pre_usage  \
0      70    0          4       1               1        1         57   
1     121    1          4       2               1        3         68   
2      86    0          4       3               1        1         44   
3     141    0          4       3               1        3         63   
4     172    0          4       2               1        2         47   

   Post_usage_1month  Latest_mon_usage  post_usage_2ndmonth  
0                 52              49.2                 57.2  
1                 59              63.6                 64.9  
2                 33              64.8                 36.3  
3                 44              56.4                 48.4  
4                 52              68.4                 57.2

In [74]:
#creating male df
df_male = df[df.sex == 0]

In [75]:
#creating female df
df_female = df[df.sex == 1]

In [76]:
#preusage
_,p_value = stats.ttest_ind(a = df_male['pre_usage'],b = df_female.pre_usage,equal_var=False)

In [77]:
print(p_value)

0.45716095076827834


In [78]:
if p_value < 0.05:
    print('Reject the null hypothesis,there is difference between mean of this two variables ')
else:
    print('Fail to Reject the null hypothesis,there is no difference between mean of this two variables ')

Fail to Reject the null hypothesis,there is no difference between mean of this two variables 


In [83]:
#post_usage
_,p_value = stats.ttest_ind(a = df_male.Post_usage_1month,b = df_female.Post_usage_1month,equal_var=False)
if p_value < 0.05:
    print('Reject the null hypothesis,there is difference between mean of this two variables ')
else:
    print('Fail to Reject the null hypothesis,there is no difference between mean of this two variables ')

Reject the null hypothesis,there is difference between mean of this two variables 


#### In preusage there is no difference in male and female in term of credit card usage
#### In postusage there is difference in male and female in term of credit card usage due to success of campaign 

# 4. Is there any relation between region and segment? 
(Hint: Finding the relationship between categorical variables and Segment)


## Chi-Square Test

- The null hypothesis states that there is no relationship between the two variables
- The alternate hypothesis states that there is relationship between the two variables

#### Using chi-square test to check relation between region and segment like whether there are dependent or not 

#### In this problem
- The null hypothesis is that there no relationship between region and segment
- The alternate hypothesis is that there is relationship between region and segment

In [30]:
df.head()

custid  sex  AqChannel  region  Marital_status  segment  pre_usage  \
0      70    0          4       1               1        1         57   
1     121    1          4       2               1        3         68   
2      86    0          4       3               1        1         44   
3     141    0          4       3               1        3         63   
4     172    0          4       2               1        2         47   

   Post_usage_1month  Latest_mon_usage  post_usage_2ndmonth  
0                 52              49.2                 57.2  
1                 59              63.6                 64.9  
2                 33              64.8                 36.3  
3                 44              56.4                 48.4  
4                 52              68.4                 57.2

In [32]:
df.segment.unique()

array([1, 3, 2], dtype=int64)

In [33]:
df.region.unique()

array([1, 2, 3], dtype=int64)

In [37]:
df_table = pd.crosstab(df['region'],df['segment'])
df_table

segment   1   2   3
region             
1        16  19  12
2        20  44  31
3         9  42   7

In [38]:
#observed_values
observed_values = df_table.values

In [39]:
observed_values

array([[16, 19, 12],
       [20, 44, 31],
       [ 9, 42,  7]], dtype=int64)

In [40]:
val = stats.chi2_contingency(df_table)
#expected_values
expected_values = val[3]

In [41]:
expected_values

array([[10.575, 24.675, 11.75 ],
       [21.375, 49.875, 23.75 ],
       [13.05 , 30.45 , 14.5  ]])

In [42]:
#dof
no_of_rows = len(df_table.iloc[0:,0])
no_of_columns = len(df_table.iloc[0,0:])
ddof = (no_of_rows-1)*(no_of_columns-1)
alpha = 0.05

In [46]:
print('dof is :',ddof)

dof is : 4


In [47]:
#chi_square_Statistic
chi_square = sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])
chi_square_statistic = chi_square[0]+chi_square[1]

In [48]:
print('chi_square_statistic is :',chi_square_statistic)

chi_square_statistic is : 10.506654260988741


In [49]:
#criticalvalue
critical_value = chi2.ppf(q=1-alpha,df=ddof)

In [50]:
print('critical value is :',critical_value)

critical value is : 9.487729036781154


In [51]:
#p_value
p_value = 1 - chi2.cdf(x = chi_square_statistic,df=ddof)

In [52]:
print('p-value: ',p_value)
print('significance level: ',alpha)
print('Degree of freedom: ',ddof)
print('chi-square statistic:-',chi_square_statistic)
print('critical_value:',critical_value)

p-value:  0.03270545264225733
significance level:  0.05
Degree of freedom:  4
chi-square statistic:- 10.506654260988741
critical_value: 9.487729036781154


In [53]:
if chi_square_statistic>=critical_value:
    print('Reject H0,There is a relationship between 2 categorical variables')
else:
    print('Fail to reject H0, There is no relationship between 2 categorial variables')
    
if p_value <= alpha:
    print('Reject H0,There is a relationship between 2 categorical variables')
else:
    print('Fail to reject H0, There is no relationship between 2 categorial variables')    

Reject H0,There is a relationship between 2 categorical variables
Reject H0,There is a relationship between 2 categorical variables


#### Reject the null hypothesis that there is relation between region and segment